apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatform
metadata:
  labels:
    app.kubernetes.io/managed-by: aap-operator
    app.kubernetes.io/name: example
    app.kubernetes.io/part-of: example
  name: example
  namespace: aap
spec:
  eda:
    disabled: false
  route_tls_termination_mechanism: Edge
  service_type: ClusterIP
  ingress_type: Route
  no_log: true
  redis_mode: standalone
  #hostname: example-aap.apps.cluster2.tide.lan
  hub:
    disabled: false
    file_storage_size: 10Gi
    file_storage_storage_class: ocs-storagecluster-cephfs
    storage_type: file
  api:
    log_level: INFO
    replicas: 1
  database:
    postgres_data_volume_init: false
    storage_requirements:
      requests:
        storage: 100Gi
  controller:
    disabled: false
  route_host: example-aap.apps.cluster2.tide.lan